### PR TITLE
Error correction : SyntaxWarning: "is" with a literal.

### PR DESCRIPTION
**Pull request by omerien**

### CODE REVIEW

**Comment by omerien** [comment]
PS: mention this as a fix please

**Review by TheTechRobo — APPROVED** [review]
Unless I'm missing something, this should work!

**Comment by omerien** [comment]
Hey, it's still an error, please merge it

**Comment by spotlightishere** [comment]
Seems like this was included in 972970458bdbb1f6f9c2822fad77546f3c96ba94:)

**Pull request closed without merging**
